### ISSUE TITLE
Phalcon RESTful API

### ISSUE THREAD

**Issue by mattdanger** [SochaDev/sochadev.github.io#1]
`@mistressofdrupal - Build a micro RESTful API using either Slim or Phalcon (private SD repo plz), make sure a base path of https://wintermute.sochadev.com/api-www exists and can handle POST and GET, reject all other verbs with a 403. Ping @natemow for SSL or alias setup or whatever on wintermute as needed. API should also make sure that cross-origin requests are handled from sochadev.github.io, sochadev.com and local.sochadev; all other domains should throw a 403. We need status (HTTP response int) and messages (array) included in all API responses. Update assets/js/app.js::theme.contactForm jQuery $.post and/or .respond handler to reflect API JSON responses.`

@tea-time If you want to do this in Phalcon then check out PWC's `routes.php` and `AjaxController` for an example of how to do this. PWC's API is not RESTful but the stuff in there will provide a good example of what you need.

If you want to do this in Slim check out the `labapi` module in the `discovery4` repo. 

Slim is more lightweight, but is laborious to query w/ a DB so you might prefer to use Phalcon depending what the API actually serves.

**Comment by natemow** [comment]
Derp...forgot to spec what I actually need here atm: a single `contact` endpoint; set `config.php` var or whatever with the actual email addy (TBD). All it should do is shoot an email off to conf'd address and send response to caller per spec.

Re: private repo -- let's use `www`; got some longer-term ideas that are not API-related at all.

**Comment by mattdanger** [comment]
This is up and running on `api.sochadev.com` you can POST a JSON object to `/contact` and it will send an email. 

`name`, `email` and `subject` keys are required.

Here is an example blob:

`{"name":"John doe","email":"asdf@email.com","subject":"Hello msg","phone":"555-555-5555","title":"president","org":"NSA","body":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}`

**Comment by mattdanger** [comment]
@natemow swiftermailer / GMail SMTP config doesn't want to send emails using the  `tracker@sochadev.com` account. It works with my `west.matt@sochadev.com` account and password. Is `0sisisJD!` the correct password?

**Comment by mattdanger** [comment]
I rewrote the API using SlimPHP. The Micro Phalcon app wouldn't populate any REQUEST vars, not sure why.

**Comment by mattdanger** [comment]
Figured out the original Phalcon micro issue. Reverted back to Micro app and did a bunch of cleanup. CORS working correctly now.

**Comment by natemow** [comment]
Satisfied with this now; thanks for banging it out.
