### ISSUE TITLE
A-Team retina Alpha image

### ISSUE THREAD

**Issue by jeffeoff** [SochaDev/sochadev.github.io#2]
Make the A-Team alpha retina friendly. Right now it looks rough in retina. If you make the original image twice as large (resolution wise) and then force background-size: to half the width, that will render the image in the same size but retina will no longer be dithered.

Or -- even better -- use a big font. If you want to keep the font file itself small, you could use http://fontello.com/ to make a custom font file with just that font and the few font-awesome icons we're using.

**Comment by natemow** [comment]
I _think_ it looks rough cuz I dl'd the `A-Team` logo and did some goofy Gimp magic wand shiz with a 1px border; I didn't actually want to use a font...the actual logo is way more legacy/cool/recognizable. And if we're gonna call ourselves "A-Team" we gd well better be using `A-Team` brand; open to suggestions here on how to improve execution -- no guff about brand-borrowing plz.
