### ISSUE TITLE
Apply seal-of-approval and point the `sochadev.com` domain

### ISSUE THREAD

**Issue by natemow** [SochaDev/sochadev.github.io#5]
To do that we'll need this stuff:
- Add a `CNAME` file to repo root with 1 line in it: `sochadev.com`. Confirm this is acknowledged under project settings (you should see "Your site is published at http://sochadev.com" in a minute or so).
- Add DNS `A` records for `192.30.252.153`, `192.30.252.154`, remove existing record.
- Add DNS `CNAME` record for `www.sochadev.com` pointing to `sochadev.github.io`.

**Comment by jasonsocha** [comment]
Made some tweaks.  Added CNAME file.  DNS updates complete.  Now we wait for propagation.  Gonna close this.
